language: python
python:
  - '2.7'
  - '3.6'
sudo: required
install:
  - pip install .
script: nosetests
deploy:
  provider: pypi
  user: "${PYPI_USERNAME}"
  password: "${PYPI_PASSWORD}"
  on:
    tags: true
