language: python
python:
  - '2.7'
  - '3.6'
sudo: required
install:
  - pip install -r requirements.txt
  - pip install -e .
script: 
  - pytest --cov=opentargets_validator --cov-report term tests/ --fulltrace
deploy:
  provider: pypi
  user: "${PYPI_USERNAME}"
  password: "${PYPI_PASSWORD}"
  on:
    tags: true

notifications:
  email:
    recipients:
    - ops@opentargets.org
    on_success: never
    on_failure: always
after_success:
  - codecov
